import { Heart, Sparkles, ShoppingBag, Calendar, Home, Info, Phone } from 'lucide-react';

export const searchData = [
  // Pages
  {
    id: 'page-home',
    type: 'Page',
    title: 'Home',
    description: 'Welcome to Ahnupha - Discover handmade chocolates.',
    path: '/',
    icon: Home
  },
  {
    id: 'page-about',
    type: 'Page',
    title: 'About Us',
    description: 'Learn about our story, values, and team.',
    path: '/about',
    icon: Info
  },
  {
    id: 'page-contact',
    type: 'Page',
    title: 'Contact Us',
    description: 'Get in touch for inquiries and bookings.',
    path: '/contact',
    icon: Phone
  },
  // Chocolate Items – Kunafa Bar first (featured), then Kunafa Chocolate
  {
    id: 'prod-kunafa-bar',
    type: 'Product',
    category: 'Chocolate',
    title: 'Kunafa Bar Chocolate',
    description: 'Delicious kunafa bar chocolate. A perfect blend of kunafa and premium chocolate, handcrafted for a unique treat. 240g.\n\n✨ Handcrafted with love\n✨ Kunafa bar chocolate\n✨ Made with love by Ahnupha Bites',
    price: 599,
    originalPrice: 699,
    offerPrice: 599,
    offerLabel: 'Special Offer · Limited',
    stock: 10,
    rating: 5.0,
    reviews: 0,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: 'Kunafa Bar Chocolate',
    image: 'https://live.staticflickr.com/65535/55113688721_f5b70b5008_b.jpg',
    images: [
      'https://live.staticflickr.com/65535/55113688721_f5b70b5008_b.jpg',
      'https://live.staticflickr.com/65535/55113895338_d71f337f28_b.jpg'
    ],
    imageFit: 'contain',
    weight: '240g'
  },
  {
    id: 'prod-assorted-chocolates',
    type: 'Product',
    category: 'Chocolate',
    title: 'Assorted Chocolates',
    description: 'A delightful mix of handcrafted assorted chocolates. 12 chocolates in a box, 125g total. Perfect for gifting and sharing.\n\n✨ Handcrafted with love\n✨ 12 chocolates in box\n✨ 125g · Premium quality\n✨ Made with love by Ahnupha Bites',
    price: 119,
    stock: 10,
    rating: 5.0,
    reviews: 0,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: 'Assorted Chocolates',
    image: 'https://live.staticflickr.com/65535/55125713306_919aee4fea_b.jpg',
    imageFit: 'contain',
    weight: '125g'
  },
  {
    id: 'prod-dry-fruit-laddu',
    type: 'Product',
    category: 'Snacks',
    title: 'Dry Fruit Laddu',
    description: 'Handcrafted with premium dry fruits. Perfect for gifting and celebrations.\n\n✨ Homemade with love\n✨ 150g · ₹169 | 300g · ₹339 | 450g · ₹509\n✨ We deliver all over India',
    price: 169,
    stock: 10,
    rating: 5.0,
    reviews: 0,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: 'Dry Fruit Laddu',
    image: 'https://live.staticflickr.com/65535/55132706673_38ccef67a6_b.jpg',
    imageFit: 'contain',
    weight: '150g / 300g / 450g',
    weightOptions: [
      { weight: '150g', price: 169 },
      { weight: '300g', price: 339 },
      { weight: '450g', price: 509 }
    ]
  },
  {
    id: 'prod-kunafa-chocolate',
    type: 'Product',
    category: 'Chocolate',
    title: 'Kunafa Chocolate',
    description: 'Premium kunafa-inspired chocolate. 16g pieces at ₹49 each. Handcrafted with care, perfect for gifting and indulgence.\n\n✨ Handcrafted with love\n✨ Premium kunafa chocolate · 16g\n✨ Delivery min 10 · Pickup no minimum\n✨ Made with love by Ahnupha Bites',
    price: 49,
    stock: 999,
    rating: 5.0,
    reviews: 0,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: 'Kunafa Chocolate',
    image: 'https://live.staticflickr.com/65535/55101111466_e0477eda3b_b.jpg',
    images: [
      'https://live.staticflickr.com/65535/55101111466_e0477eda3b_b.jpg',
      'https://live.staticflickr.com/65535/55101382289_c09e111c1b_b.jpg'
    ],
    imageFit: 'contain',
    weight: '16g',
    minOrderForDelivery: 10
  },
  {
    id: 'prod-c16',
    type: 'Product',
    category: 'Chocolate',
    title: 'Truffle Temptation Box',
    description: 'Indulge in our handcrafted chocolate truffles made using premium. Each truffle is topped with a delightful mix of nuts and sprinkles, offering a perfect balance of taste and texture.\n\nEvery piece is individually wrapped for hygiene and packed in a premium gift box — perfect for celebrations, gifting, and sweet moments. 🍫✨\n\n✨ Handcrafted with care\n✨ Premium ingredients\n✨ Individually wrapped truffles\n✨ Perfect for gifting\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight variations in design and finish may occur, making every box unique.',
    price: 399,
    stock: 10,
    rating: 5.0,
    reviews: 72,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Truffle Temptation Box",
    image: "https://live.staticflickr.com/65535/55065580042_28ef925554.jpg",
    imageFit: 'contain', // Use contain instead of cover to show full image
    weight: '180g'
  },
  {
    id: 'prod-c1',
    type: 'Product',
    category: 'Chocolate',
    title: 'Valentine Special Photo Chocolates',
    description: 'Celebrate love with our handcrafted photo chocolates, made with crunchy nuts. Each chocolate is individually wrapped and placed inside a beautifully designed gift box, making it perfect for Valentine\'s Day and special surprises.\n\nEvery piece is made with care to give a rich taste, smooth finish, and a memorable gifting experience. ❤️🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped for hygiene\n✨ Perfect for gifting & surprises\n✨ Made by Ahnupha Bites\n\nThis is a handcrafted product. Slight color variations may occur, making every box unique.',
    price: 339,
    stock: 10,
    rating: 5.0,
    reviews: 150,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Valentine Special Photo Chocolates",
    image: "https://live.staticflickr.com/65535/55065580272_d17df12fca_b.jpg",
    imageFit: 'contain', // Use contain to show full image
    weight: '100g'
  },
  {
    id: 'prod-c2',
    type: 'Product',
    category: 'Chocolate',
    title: 'Will You Be My Valentine Chocolate Box',
    description: 'Say it sweetly with our handcrafted message chocolates, made using premium ingredients and topped with customized Valentine words. Lightly blended with crunchy nuts, each chocolate is carefully wrapped and placed inside a beautifully designed gift box.\n\nThe entire box is hygienically wrapped, making it a perfect surprise for Valentine\'s Day and special moments. ❤️🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped message chocolates\n✨ Perfect for proposals & surprises\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every box unique.',
    price: 259,
    stock: 10,
    rating: 5.0,
    reviews: 98,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Will You Be My Valentine Chocolate Box",
    image: "https://live.staticflickr.com/65535/55066669203_59a30a9849.jpg",
    imageFit: 'contain',
    weight: '66g'
  },
  {
    id: 'prod-c3',
    type: 'Product',
    category: 'Chocolate',
    title: 'Love Values Chocolate Box',
    description: 'Some feelings are better said with meaning, not just words.\n\nOur handcrafted message chocolates are made using premium ingredients and thoughtfully designed with meaningful words — Love, Care, Trust, Respect, Passion, and Forever — the true foundations of a beautiful relationship.\n\nEach chocolate is individually wrapped with customized foil, carefully arranged in a premium gift box, and hygienically sealed with wrap to preserve freshness and quality.\n\nPerfect for Valentine\'s Day, anniversaries, proposals, or simply to remind someone what they truly mean to you. ❤️🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped message chocolates\n✨ Meaningful gifting experience\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every box unique.',
    price: 259,
    stock: 10,
    rating: 5.0,
    reviews: 120,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Love Values Chocolate Box",
    image: "https://live.staticflickr.com/65535/55066736049_58b3b7b12a.jpg",
    imageFit: 'contain',
    weight: '66g'
  },
  {
    id: 'prod-c24',
    type: 'Product',
    category: 'Chocolate',
    title: 'Forever Feelings Chocolate Box',
    description: 'Celebrate meaningful relationships with our handcrafted message chocolates, featuring five beautifully wrapped word chocolates and one premium centre chocolate to complete the message of love.\n\nMade using premium ingredient with crunchy nuts, each piece is wrapped with customised foil and carefully arranged in a premium gift box. The entire box is hygienically wrapped to ensure freshness and quality.\n\nPerfect for Valentine\'s Day, anniversaries, proposals, or heartfelt gifting. ❤️🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped message chocolates\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every box unique.',
    price: 279,
    stock: 10,
    rating: 5.0,
    reviews: 119,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Forever Feelings Chocolate Box",
    image: "https://live.staticflickr.com/65535/55066484351_a7ce26ac6a.jpg",
    imageFit: 'contain',
    weight: '64g'
  },
  {
    id: 'prod-c22',
    type: 'Product',
    category: 'Chocolate',
    title: 'I ❤️ U Chocolate Box',
    description: 'Sometimes, a small box says the biggest words.\n\nOur handcrafted mini chocolate box features three personalised message chocolates — \'I\', \'❤️\', \'U\' — made using premium ingredients and lightly blended with crunchy nuts.\n\nEach chocolate is individually wrapped with customised foil, neatly placed inside a heart-shaped box, and hygienically wrapped to preserve freshness.\n\nPerfect for Valentine\'s Day, surprises, proposals, or sweet everyday gifting. 💕🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped message chocolates\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every box unique.',
    price: 179,
    stock: 10,
    rating: 5.0,
    reviews: 81,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "I ❤️ U Chocolate Box",
    image: "https://live.staticflickr.com/65535/55065580212_8f0cd478a5.jpg",
    imageFit: 'contain',
    weight: '33g'
  },
  {
    id: 'prod-c4',
    type: 'Product',
    category: 'Chocolate',
    title: 'Heart Chocolate Box',
    description: '9 handcrafted heart chocolates in a premium gift box. A rich mix of dark, milk, and white chocolates with crunchy nut fillings. Perfect for gifting, surprises, and sweet emotions.\n\nThis is a handcrafted marble product.\nSlight color and design variations may occur, making every box unique.',
    price: 349,
    stock: 10,
    rating: 5.0,
    reviews: 95,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Heart Chocolate Box",
    image: "https://live.staticflickr.com/65535/55066838880_b964b35a78_b.jpg",
    imageFit: 'contain',
    weight: '63g'
  },
  {
    id: 'prod-c5',
    type: 'Product',
    category: 'Chocolate',
    title: 'Marble Hearts – Signature Box',
    description: '9 handcrafted marble heart chocolates in a premium gift box. Made with dark, milk & white chocolates and crunchy nut fillings. Each box is unique with natural marble patterns.\n\nThis is a handcrafted marble product.\nSlight color and design variations may occur, making every box unique.',
    price: 349,
    stock: 10,
    rating: 5.0,
    reviews: 108,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Marble Hearts – Signature Box",
    image: "https://live.staticflickr.com/65535/55066669258_01c231a415_b.jpg",
    imageFit: 'contain',
    weight: '63g'
  },
  {
    id: 'prod-c6',
    type: 'Product',
    category: 'Chocolate',
    title: 'Mini Marble Hearts',
    description: 'Ahnupha Mini Marble Hearts – 5 Piece Box\nA premium slim box of 5 handcrafted marble heart chocolates made with dark, milk & white chocolates and light nut fillings. Each box is unique in design.\n\nThis is a handcrafted marble product. Slight color and design variations may occur, making every box unique.',
    price: 199,
    stock: 10,
    rating: 5.0,
    reviews: 95,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Mini Marble Hearts",
    image: "https://live.staticflickr.com/65535/55066484376_ebeb494351_b.jpg",
    imageFit: 'contain',
    weight: '35g'
  },
  {
    id: 'prod-c7',
    type: 'Product',
    category: 'Chocolate',
    title: 'Heart Bliss Chocolate Box',
    description: 'Express your love with our handcrafted heart-shaped chocolates, made using premium ingredients and gently filled with crunchy nuts.\nEach box is carefully packed to give you a rich taste, smooth texture, and a beautiful gifting experience.\n\nPerfect for gifting, surprises, and special moments. 💝\n\nThis is a handcrafted marble product.\nSlight color and design variations may occur, making every box unique.',
    price: 199,
    stock: 10,
    rating: 5.0,
    reviews: 102,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Heart Bliss Chocolate Box",
    image: "https://live.staticflickr.com/65535/55066736134_554a34d437_b.jpg",
    imageFit: 'contain',
    weight: '35g'
  },
  {
    id: 'prod-c9',
    type: 'Product',
    category: 'Chocolate',
    title: 'Love Duo Chocolate',
    description: 'Celebrate love with our handcrafted chocolate duo, made using premium ingredients and delicately designed with romantic heart and rose patterns. Lightly blended with crunchy nuts, this combo is perfect for gifting someone special.\n\nEach chocolate is individually wrapped for hygiene and carefully packed to give a rich taste and premium gifting experience.\n\nPerfect for couples, surprises, and Valentine gifting. ❤️🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped\n✨ Perfect couple gift\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every box unique.',
    price: 299,
    stock: 10,
    rating: 5.0,
    reviews: 103,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Love Duo Chocolate",
    image: "https://live.staticflickr.com/65535/55066838715_70e3785504.jpg",
    imageFit: 'contain',
    weight: '89g'
  },
  {
    id: 'prod-c10',
    type: 'Product',
    category: 'Chocolate',
    title: 'Love Duo Chocolate',
    description: 'Celebrate love with our handcrafted chocolate duo, made using premium ingredients and delicately designed with romantic heart and rose patterns. Lightly blended with crunchy nuts, this combo is perfect for gifting someone special.\n\nEach chocolate is individually wrapped for hygiene and carefully packed to give a rich taste and premium gifting experience.\n\nPerfect for couples, surprises, and Valentine gifting. ❤️🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped\n✨ Perfect couple gift\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every box unique.',
    price: 299,
    stock: 10,
    rating: 5.0,
    reviews: 76,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Love Duo Chocolate",
    image: "https://live.staticflickr.com/65535/55066484271_176681b843.jpg",
    imageFit: 'contain',
    weight: '89g'
  },
  {
    id: 'prod-c11',
    type: 'Product',
    category: 'Chocolate',
    title: 'Love Duo Chocolate',
    description: 'Celebrate love with our handcrafted chocolate duo, made using premium ingredients and delicately designed with romantic heart and rose patterns. Lightly blended with crunchy nuts, this combo is perfect for gifting someone special.\n\nEach chocolate is individually wrapped for hygiene and carefully packed to give a rich taste and premium gifting experience.\n\nPerfect for couples, surprises, and Valentine gifting. ❤️🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped\n✨ Perfect couple gift\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every box unique.',
    price: 299,
    stock: 10,
    rating: 5.0,
    reviews: 142,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Love Duo Chocolate",
    image: "https://live.staticflickr.com/65535/55066669018_c09fcb15b3.jpg",
    imageFit: 'contain',
    weight: '89g'
  },
  {
    id: 'prod-c15',
    type: 'Product',
    category: 'Chocolate',
    title: 'Love Duo Chocolate',
    description: 'Celebrate love with our handcrafted chocolate duo, made using premium ingredients and delicately designed with romantic heart and rose patterns. Lightly blended with crunchy nuts, this combo is perfect for gifting someone special.\n\nEach chocolate is individually wrapped for hygiene and carefully packed to give a rich taste and premium gifting experience.\n\nPerfect for couples, surprises, and Valentine gifting. ❤️🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped\n✨ Perfect couple gift\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every box unique.',
    price: 299,
    stock: 10,
    rating: 5.0,
    reviews: 84,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Love Duo Chocolate",
    image: "https://live.staticflickr.com/65535/55066735934_c34be3213c.jpg",
    imageFit: 'contain',
    weight: '89g'
  },
  {
    id: 'prod-c20',
    type: 'Product',
    category: 'Chocolate',
    title: 'Love Duo Chocolate',
    description: 'Celebrate love with our handcrafted chocolate duo, made using premium ingredients and delicately designed with romantic heart and rose patterns. Lightly blended with crunchy nuts, this combo is perfect for gifting someone special.\n\nEach chocolate is individually wrapped for hygiene and carefully packed to give a rich taste and premium gifting experience.\n\nPerfect for couples, surprises, and Valentine gifting. ❤️🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped\n✨ Perfect couple gift\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every box unique.',
    price: 299,
    stock: 10,
    rating: 5.0,
    reviews: 65,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Love Duo Chocolate",
    image: "https://live.staticflickr.com/65535/55066484301_7958df41e0.jpg",
    imageFit: 'contain',
    weight: '89g'
  },
  {
    id: 'prod-c23',
    type: 'Product',
    category: 'Chocolate',
    title: 'Love Duo Chocolate',
    description: 'Celebrate love with our handcrafted chocolate duo, made using premium ingredients and delicately designed with romantic heart and rose patterns. Lightly blended with crunchy nuts, this combo is perfect for gifting someone special.\n\nEach chocolate is individually wrapped for hygiene and carefully packed to give a rich taste and premium gifting experience.\n\nPerfect for couples, surprises, and Valentine gifting. ❤️🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped\n✨ Perfect couple gift\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every box unique.',
    price: 299,
    stock: 10,
    rating: 5.0,
    reviews: 92,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Love Duo Chocolate",
    image: "https://live.staticflickr.com/65535/55066669088_41dd3a1a34.jpg",
    imageFit: 'contain',
    weight: '89g'
  },
  {
    id: 'lduo1',
    type: 'Product',
    category: 'Chocolate',
    title: 'Love Duo Chocolate',
    description: 'Celebrate love with our handcrafted chocolate duo, made using premium ingredients and delicately designed with romantic heart and rose patterns. Lightly blended with crunchy nuts, this combo is perfect for gifting someone special.\n\nEach chocolate is individually wrapped for hygiene and carefully packed to give a rich taste and premium gifting experience.\n\nPerfect for couples, surprises, and Valentine gifting. ❤️🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped\n✨ Perfect couple gift\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every box unique.',
    price: 299,
    stock: 10,
    rating: 5.0,
    reviews: 78,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Love Duo Chocolate",
    image: "https://live.staticflickr.com/65535/55066838645_134356b61c_b.jpg",
    imageFit: 'contain',
    weight: '89g'
  },
  {
    id: 'lduo2',
    type: 'Product',
    category: 'Chocolate',
    title: 'Love Duo Chocolate',
    description: 'Celebrate love with our handcrafted chocolate duo, made using premium ingredients and delicately designed with romantic heart and rose patterns. Lightly blended with crunchy nuts, this combo is perfect for gifting someone special.\n\nEach chocolate is individually wrapped for hygiene and carefully packed to give a rich taste and premium gifting experience.\n\nPerfect for couples, surprises, and Valentine gifting. ❤️🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped\n✨ Perfect couple gift\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every box unique.',
    price: 299,
    stock: 10,
    rating: 5.0,
    reviews: 88,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Love Duo Chocolate",
    image: "https://live.staticflickr.com/65535/55066669048_a7773624be_b.jpg",
    imageFit: 'contain',
    weight: '89g'
  },
  {
    id: 'lduo3',
    type: 'Product',
    category: 'Chocolate',
    title: 'Love Duo Chocolate',
    description: 'Celebrate love with our handcrafted chocolate duo, made using premium ingredients and delicately designed with romantic heart and rose patterns. Lightly blended with crunchy nuts, this combo is perfect for gifting someone special.\n\nEach chocolate is individually wrapped for hygiene and carefully packed to give a rich taste and premium gifting experience.\n\nPerfect for couples, surprises, and Valentine gifting. ❤️🍫\n\n✨ Handcrafted with love\n✨ Premium quality\n✨ Individually wrapped\n✨ Perfect couple gift\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every box unique.',
    price: 299,
    stock: 10,
    rating: 5.0,
    reviews: 95,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Love Duo Chocolate",
    image: "https://live.staticflickr.com/65535/55066484261_eb70b36674_b.jpg",
    imageFit: 'contain',
    weight: '89g'
  },
  {
    id: 'prod-c8',
    type: 'Product',
    category: 'Chocolate',
    title: 'With Love Rose Chocolate',
    description: 'Express your feelings with our handcrafted rose chocolate, delicately designed with a blooming rose and subtle nut crunch.\n\nEach piece is carefully crafted, cling-wrapped for hygiene, and packed to give a rich taste with an elegant gifting experience.\n\nPerfect for gifting, surprises, and special moments. 🌹🍫\n\n✨ Handcrafted\n✨ Premium quality \n✨ Made with love by Ahnupha Bites\n✨ Hygienically wrapped\n\nThis is a handcrafted product. Slight color variations may occur, making every piece unique.',
    stock: 10,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "With Love Rose Chocolate",
    image: "https://live.staticflickr.com/65535/55066735899_fecc096b4c.jpg",
    imageFit: 'contain'
  },
  {
    id: 'prod-c17',
    type: 'Product',
    category: 'Chocolate',
    title: 'With Love Rose Chocolate',
    description: 'Express your feelings with our handcrafted rose chocolate, delicately designed with a blooming rose and subtle nut crunch.\n\nEach piece is carefully crafted, cling-wrapped for hygiene, and packed to give a rich taste with an elegant gifting experience.\n\nPerfect for gifting, surprises, and special moments. 🌹🍫\n\n✨ Handcrafted\n✨ Premium quality \n✨ Made with love by Ahnupha Bites\n✨ Hygienically wrapped\n\nThis is a handcrafted product. Slight color variations may occur, making every piece unique.',
    stock: 10,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "With Love Rose Chocolate",
    image: "https://live.staticflickr.com/65535/55065580147_71af101067.jpg",
    imageFit: 'contain'
  },
  {
    id: 'prod-c19',
    type: 'Product',
    category: 'Chocolate',
    title: 'With Love Rose Chocolate',
    description: 'Express your feelings with our handcrafted rose chocolate, delicately designed with a blooming rose and subtle nut crunch.\n\nEach piece is carefully crafted, cling-wrapped for hygiene, and packed to give a rich taste with an elegant gifting experience.\n\nPerfect for gifting, surprises, and special moments. 🌹🍫\n\n✨ Handcrafted\n✨ Premium quality \n✨ Made with love by Ahnupha Bites\n✨ Hygienically wrapped\n\nThis is a handcrafted product. Slight color variations may occur, making every piece unique.',
    stock: 10,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "With Love Rose Chocolate",
    image: "https://live.staticflickr.com/65535/55066484266_2a935c2cd2.jpg",
    imageFit: 'contain'
  },
  {
    id: 'prod-c12',
    type: 'Product',
    category: 'Chocolate',
    title: 'Heartbeat Chocolate Bar',
    description: 'Fall in love with every bite of our handcrafted chocolate bar, made using premium ingredients and  Gently blended with crunchy nuts, this bar is designed to make your gifting moments extra special.\n\nEach piece is individually wrapped for hygiene and carefully packed to give a rich taste and premium feel.\n\nPerfect for gifting, surprises, and sweet moments. 🤍🍫\n\n\n\n✨ Handcrafted with love\n✨ Premium quality \n✨ Individually wrapped\n✨ Made with love by Ahnupha Bites\n✨ Perfect gift chocolate\n\nThis is a handcrafted product. Slight color variations may occur, making every piece unique.',
    price: 179,
    stock: 10,
    rating: 5.0,
    reviews: 91,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Heartbeat Chocolate Bar",
    image: "https://live.staticflickr.com/65535/55066735829_3462a0eb9d.jpg",
    imageFit: 'contain',
    weight: '48g'
  },
  {
    id: 'prod-c14',
    type: 'Product',
    category: 'Chocolate',
    title: 'Heartbeat Chocolate Bar',
    description: 'Fall in love with every bite of our handcrafted chocolate bar, made using premium ingredients and  Gently blended with crunchy nuts, this bar is designed to make your gifting moments extra special.\n\nEach piece is individually wrapped for hygiene and carefully packed to give a rich taste and premium feel.\n\nPerfect for gifting, surprises, and sweet moments. 🤍🍫\n\n\n\n✨ Handcrafted with love\n✨ Premium quality \n✨ Individually wrapped\n✨ Made with love by Ahnupha Bites\n✨ Perfect gift chocolate\n\nThis is a handcrafted product. Slight color variations may occur, making every piece unique.',
    price: 179,
    stock: 10,
    rating: 5.0,
    reviews: 68,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Heartbeat Chocolate Bar",
    image: "https://live.staticflickr.com/65535/55066669053_2cb091b261.jpg",
    imageFit: 'contain',
    weight: '48g'
  },
  {
    id: 'hrtb1',
    type: 'Product',
    category: 'Chocolate',
    title: 'Heartbeat Chocolate Bar',
    description: 'Fall in love with every bite of our handcrafted chocolate bar, made using premium ingredients and  Gently blended with crunchy nuts, this bar is designed to make your gifting moments extra special.\n\nEach piece is individually wrapped for hygiene and carefully packed to give a rich taste and premium feel.\n\nPerfect for gifting, surprises, and sweet moments. 🤍🍫\n\n\n\n✨ Handcrafted with love\n✨ Premium quality \n✨ Individually wrapped\n✨ Made with love by Ahnupha Bites\n✨ Perfect gift chocolate\n\nThis is a handcrafted product. Slight color variations may occur, making every piece unique.',
    price: 179,
    stock: 10,
    rating: 5.0,
    reviews: 85,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Heartbeat Chocolate Bar",
    image: "https://live.staticflickr.com/65535/55066484126_8703a41030_b.jpg",
    imageFit: 'contain',
    weight: '48g'
  },
  {
    id: 'prod-c25',
    type: 'Product',
    category: 'Chocolate',
    title: 'Love Bar',
    description: 'Turn a sweet memory with our handcrafted personalised chocolate bar. Made using premium ingredients and highlighted with smooth white chocolate lettering, each bar is lightly topped with crunchy nuts for added texture and taste.\n\nCarefully wrapped for hygiene and packed to preserve freshness, this chocolate makes a perfect gift for birthdays, anniversaries, Valentine\'s Day, or special surprises.\n\n✨ Handcrafted with love\n✨ Premium quality \n✨ Custom name design \n✨ Hygienically wrapped\n✨ Made with love by Ahnupha Bites\n\nThis is a handcrafted product. Slight color and design variations may occur, making every piece unique.',
    price: 199,
    stock: 10,
    rating: 5.0,
    reviews: 125,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Love Bar",
    image: "https://live.staticflickr.com/65535/55066669178_e7411def9f_b.jpg",
    imageFit: 'contain',
    weight: '72g'
  },
  {
    id: 'prod-kunafa-wrap-custom',
    type: 'Product',
    category: 'Chocolate',
    title: 'Kunafa chocolate wrap customization',
    description: 'Custom kunafa chocolate wraps. Order in packs — 1 pack costs ₹29. Minimum order 14 packs. Perfect for events and gifting.\n\n✨ Handcrafted with love\n✨ Wrap customization\n✨ Min order 14 packs\n✨ Made with love by Ahnupha Bites',
    price: 29,
    stock: 999,
    rating: 5.0,
    reviews: 0,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: 'Kunafa chocolate wrap customization',
    image: 'https://live.staticflickr.com/65535/55101111466_e0477eda3b_b.jpg',
    images: [
      'https://live.staticflickr.com/65535/55101111466_e0477eda3b_b.jpg',
      'https://live.staticflickr.com/65535/55101382289_c09e111c1b_b.jpg'
    ],
    imageFit: 'contain',
    isPremiumCustom: true,
    minOrderPacks: 14,
    pricePerPack: 29,
    comingSoon: true // price 29 per pack stored above
  },
  {
    id: 'prod-personalised-bar',
    type: 'Product',
    category: 'Chocolate',
    isNew: true,
    title: 'Dryfruits overloaded bar with name',
    description: 'Handcrafted chocolate bar loaded with dry fruits and your name. Choose your base, add one name (up to 10 letters), and make it yours. Perfect for gifting.\n\n✨ Handcrafted with love\n✨ Premium dry fruits\n✨ Your name on bar\n✨ Made with love by Ahnupha Bites',
    price: 299,
    stock: 999,
    rating: 5.0,
    reviews: 0,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Dryfruits overloaded bar with name",
    image: "https://live.staticflickr.com/65535/55077670852_dff2fce361_b.jpg",
    images: [
      "https://live.staticflickr.com/65535/55077670852_dff2fce361_b.jpg",
      "https://live.staticflickr.com/65535/55080104625_466cf0f8c7_b.jpg"
    ],
    twoBarBoxImage: "https://live.staticflickr.com/65535/55079941708_f6384a97cd_b.jpg",
    twoBarBoxImages: [
      "https://live.staticflickr.com/65535/55079941708_f6384a97cd_b.jpg"
    ],
    imageFit: 'contain',
    isPremiumCustom: true,
    customNameOnBar: true,
    nameOnBarMaxLength: 10,
    baseOptions: [
      { id: 'dark', label: 'Dark Chocolate', imageIndex: 0 },
      { id: 'milk', label: 'Milk Chocolate', imageIndex: 1 }
    ],
    seedsOptions: [
      { id: 'badam', label: 'Badam', mandatory: true },
      { id: 'kaju', label: 'Kaju' },
      { id: 'black-kismis', label: 'Black Kismis' },
      { id: 'pumpkin-seeds', label: 'Pumpkin Seeds' },
      { id: 'cranberry', label: 'Cranberry' },
      { id: 'walnuts', label: 'Walnuts' },
      { id: 'watermelon-seeds', label: 'Watermelon Seeds' },
      { id: 'pista', label: 'Pista' },
      { id: 'dry-strawberries', label: 'Dry Strawberries' }
    ]
  },
  {
    id: 'prod-couples-name',
    type: 'Product',
    category: 'Chocolate',
    title: 'Couples name chocolate',
    description: 'A chocolate bar with both your names. Choose your base, add first and second name (up to 8 letters each). Perfect for anniversaries and couples.\n\n✨ Handcrafted with love\n✨ Two names on bar\n✨ Made with love by Ahnupha Bites',
    price: 299,
    stock: 999,
    rating: 5.0,
    reviews: 0,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Couples name chocolate",
    image: "https://live.staticflickr.com/65535/55092912929_23b607c864_b.jpg",
    imageFit: 'contain',
    isPremiumCustom: true,
    customNameOnBar: true,
    twoNames: true,
    nameOnBarMaxLength: 8,
    baseOptions: [
      { id: 'dark', label: 'Dark Chocolate', imageIndex: 0 },
      { id: 'milk', label: 'Milk Chocolate', imageIndex: 1 }
    ]
  },
  {
    id: 'prod-first-letters-couple',
    type: 'Product',
    category: 'Chocolate',
    title: 'First letters couple chocolate',
    description: 'Chocolate bar with your initials. Choose your base and add first letter of each name. Perfect for couples.\n\n✨ Handcrafted with love\n✨ First letters on bar\n✨ Made with love by Ahnupha Bites',
    price: 299,
    stock: 999,
    rating: 5.0,
    reviews: 0,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "First letters couple chocolate",
    image: "https://live.staticflickr.com/65535/55084177241_8a99367932_b.jpg",
    imageFit: 'contain',
    isPremiumCustom: true,
    firstLettersCouple: true,
    baseOptions: [
      { id: 'dark', label: 'Dark Chocolate', imageIndex: 0 },
      { id: 'milk', label: 'Milk Chocolate', imageIndex: 1 }
    ]
  },
  {
    id: 'prod-custom-text',
    type: 'Product',
    category: 'Chocolate',
    title: 'Custom text on chocolate',
    description: 'Chocolate bar with your custom text. Choose your base and type any message (e.g. Thank You, Congrats).\n\n✨ Handcrafted with love\n✨ Your text on bar\n✨ Made with love by Ahnupha Bites',
    price: 299,
    stock: 999,
    rating: 5.0,
    reviews: 0,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Custom text on chocolate",
    image: "https://live.staticflickr.com/65535/55077670852_dff2fce361_b.jpg",
    imageFit: 'contain',
    isPremiumCustom: true,
    customTextOnChocolate: true,
    customTextMaxLength: 20,
    baseOptions: [
      { id: 'dark', label: 'Dark Chocolate', imageIndex: 0 },
      { id: 'milk', label: 'Milk Chocolate', imageIndex: 1 }
    ]
  },
  {
    id: 'prod-birthday-wishes',
    type: 'Product',
    category: 'Chocolate',
    isNew: true,
    title: 'Birthday wishes chocolate',
    description: 'Chocolate bar with your birthday message. Choose flowers or dry fruits topping, then add your wish (e.g. Happy Birthday, Best Wishes).\n\n✨ Handcrafted with love\n✨ Custom wish on bar\n✨ Made with love by Ahnupha Bites',
    price: 299,
    stock: 999,
    rating: 5.0,
    reviews: 0,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: "Birthday wishes chocolate",
    image: "https://live.staticflickr.com/65535/55104643353_a8f81e2cc1_b.jpg",
    images: [
      "https://live.staticflickr.com/65535/55104643353_a8f81e2cc1_b.jpg",
      "https://live.staticflickr.com/65535/55104643378_498fda23c1_b.jpg"
    ],
    imageFit: 'contain',
    isPremiumCustom: true,
    birthdayWishes: true,
    customTextMaxLength: 30,
    baseOptions: [
      { id: 'dry-fruits', label: 'Dry Fruits', imageIndex: 1 },
      { id: 'flowers', label: 'Flowers', imageIndex: 0 }
    ],
    baseOptionsLabel: '1. Choose flowers or dry fruits'
  },
  {
    id: 'prod-birthday-wishes-girl',
    type: 'Product',
    category: 'Chocolate',
    isNew: true,
    title: 'Birthday wishes with girl pic',
    description: 'Chocolate bar with your birthday message and girl design. Choose flowers or dry fruits topping, then add your wish (e.g. Happy Birthday, Best Wishes).\n\n✨ Handcrafted with love\n✨ Custom wish on bar\n✨ Made with love by Ahnupha Bites',
    price: 299,
    stock: 999,
    rating: 5.0,
    reviews: 0,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: 'Birthday wishes with girl pic',
    image: 'https://live.staticflickr.com/65535/55106767827_a28360c44d_b.jpg',
    imageFit: 'contain',
    isPremiumCustom: true,
    birthdayWishes: true,
    customTextMaxLength: 30
  },
  {
    id: 'prod-princess-heart',
    type: 'Product',
    category: 'Chocolate',
    isNew: true,
    title: 'Princess Heart Chocolate',
    description: 'Elegant Princess Heart Chocolate. Handcrafted with love, perfect for gifting.\n\n✨ Handcrafted with love\n✨ Made with love by Ahnupha Bites',
    price: 299,
    stock: 999,
    rating: 5.0,
    reviews: 0,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: 'Princess Heart Chocolate',
    image: 'https://live.staticflickr.com/65535/55109842715_0605586d17_b.jpg',
    imageFit: 'contain',
    isPremiumCustom: true,
    giftWrapOnly: true
  },
  {
    id: 'prod-small-bites-wrap-chocolate',
    type: 'Product',
    category: 'Chocolate',
    isNew: true,
    title: 'Small Bites with Wrap and Chocolate',
    description: 'Handcrafted small bites wrapped in chocolate. Choose your chocolate type (Kunafa, Almond, or Cashew) and size. Custom design available — contact on WhatsApp for design requirements.\n\n✨ Handcrafted with love\n✨ Choose chocolate type & grams\n✨ Custom wrap design — contact WhatsApp\n✨ Min order 20 packs\n✨ Made with love by Ahnupha Bites',
    price: 19,
    stock: 999,
    rating: 5.0,
    reviews: 0,
    path: '/candy-chocolate',
    icon: ShoppingBag,
    imageAlt: 'Small Bites with Wrap and Chocolate',
    image: 'https://live.staticflickr.com/65535/55119989943_769efa09b8_b.jpg',
    images: [
      'https://live.staticflickr.com/65535/55119989943_769efa09b8_b.jpg',
      'https://live.staticflickr.com/65535/55120054529_019e258094_b.jpg',
      'https://live.staticflickr.com/65535/55120183945_0515f6c58f_b.jpg'
    ],
    imageFit: 'contain',
    isPremiumCustom: true,
    smallBitesWithWrap: true,
    minOrderPacks: 20,
    whatsappDesignContact: true,
    chocolateTypeOptions: [
      { id: 'kunafa', label: 'Kunafa', gramOptions: [{ weight: '16g', price: 49 }] },
      { id: 'almond', label: 'Almond', gramOptions: [{ weight: '10g', price: 19 }, { weight: '16g', price: 29 }] },
      { id: 'cashew', label: 'Cashew', gramOptions: [{ weight: '10g', price: 19 }, { weight: '16g', price: 29 }] }
    ]
  },
];